# Generated by Django 5.1.1 on 2024-11-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0003_alter_bookings_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="cast",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="movie",
            name="certificate",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="movie",
            name="formats",
            field=models.CharField(max_length=200),
        ),
    ]
