# Generated by Django 5.1.1 on 2024-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0004_alter_movie_cast_alter_movie_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
