# Generated by Django 5.1.1 on 2024-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0006_alter_bookings_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="card_type",
            new_name="month",
        ),
        migrations.AddField(
            model_name="payment",
            name="year",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
