# Generated by Django 5.1.1 on 2024-12-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0007_rename_card_type_payment_month_payment_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.CharField(default=0, max_length=200),
        ),
    ]
