# Generated by Django 5.1.1 on 2024-12-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0008_movie_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
            ],
        ),
    ]
