# Generated by Django 5.1.1 on 2024-12-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0009_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="image",
            field=models.ImageField(default=0, upload_to="qr_codes/"),
        ),
    ]
