# Generated by Django 5.1.1 on 2024-12-11 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0012_alter_bookings_qr_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrededItem",
        ),
    ]
